version: '3.4'
services:
  sugu-ui:
    build:
      context: .
      dockerfile: ./packages/sugu-ui/Dockerfile
      target: dev
    ports:
      - '3000:3000'
      - '35729:35729'
    stdin_open: true
    depends_on:
      - sugu-services
    environment: []
    ulimits:
      nofile:
        soft: 98304
        hard: 98304
  sugu-services:
    build:
      context: .
      dockerfile: ./packages/sugu-services/Dockerfile
      target: dev
    ports:
      - '3001:3000'
      - '9229:9229'
    environment: []
    ulimits:
      nofile:
        soft: 98304
        hard: 98304
    env_file: ./packages/sugu-services/.env
