# Overrides docker-compose.yml.
version: '3.4'

services:
  sugu-ui:
    container_name: sugu-ui
    volumes:
      - ./packages/sugu-ui:/srv/sugu-ui
      # https://jdlm.info/articles/2019/09/06/lessons-building-node-app-docker.html
      - sugu-ui-node_modules:/srv/sugu-ui/node_modules
  sugu-services:
    container_name: sugu-services
    volumes:
      - ./packages/sugu-services:/srv/sugu-services
      - sugu-services-node_modules:/srv/sugu-services/node_modules
# https://jdlm.info/articles/2019/09/06/lessons-building-node-app-docker.html
volumes:
    sugu-ui-node_modules:
    sugu-services-node_modules:
