version: '3.4'
services:
  # sugu-services:
  #   build:
  #     context: .
  #     dockerfile: ./packages/sugu-services/Dockerfile
  #   ports:
  #     - '3001:3000'
  #     - '9229:9229'
  #   environment: []
  #   ulimits:
  #     nofile:
  #       soft: 98304
  #       hard: 98304

  sugu-ui:
    build:
      context: .
      dockerfile: ./packages/sugu-ui/Dockerfile
      target: dev
    ports:
      - '3000:3000'
      - '35729:35729'
    stdin_open: true
    environment: []
    ulimits:
      nofile:
        soft: 98304
        hard: 98304
